### ISSUE TITLE
NOT AN ISSUE: How to enable WebP Support in GD (Plesk) ?

### ISSUE THREAD

**Issue by Hotte512** [shyim/ShyimWebP#1]
SORRY for thist jerk Question..

but do you have a clou how to enable webp support for GD in Plesk (they don't)
(Don't like to install a seperate php handler, spend enought time with that)

But if.. i have to compile my own php-handler would i add --with-vpx-dir=DIR or --with-webp-dir ?

THX

**Comment by shyim** [comment]
Hey,
I don't use plesk but forum threads saying you need a custom PHP handler.
The option --with-webp-dir should be enough, but you have to install at first the webp devel files

**Comment by shyim** [comment]
You could also use packages from https://deb.sury.org/. It has webp support

**Comment by Hotte512** [comment]
Thanks a lot!
That was the only solution I found, but a custom php-handler just to enable GD with WebP support is like getting a cow for a glas of milk ;)

And I already wasted much time to register custom handler mod_php70 to spend my ram and hopefully speed up the system... :-D
Result u can not register custom (secondary or exchange for default mod_php5) mod_php handler in plesk, also it does not support http/2 for apache :(

I rethink using plesk now... it's nice to have BUT...

**Comment by shyim** [comment]
I am using since 2 months ispconfig, i like it pretty well and its opensource not like plesk :)

**Comment by Hotte512** [comment]
Yeah, i'll setup a testsystem and give it a try...
Plesk is a nice easy system, but when it comes to PHP/APACHE/NGINX Config it'll start to make problems.
it begins with finding the right config file which will not be owerwritten... you can not access them from the backend so nice to have a nice Backend...

they realy enable http/2 via setting nginx as a proxy :-s
if i try to setup NGINX for Shopware i went crazy :-D

And now GD with WebP, as i like your Plugin's cause they 'have one's finger on the pulse of the time'
I directly wanted to test it ;)

**Comment by shyim** [comment]
For shopware on nginx is a very well configuration from bcremer available on github.
Newer apache versions also have http2 also with h2push. h2push is on nginx only available on nginx plus :(

**Comment by Hotte512** [comment]
I know, but you can not insert the config from bcremer to plesk and suggest it to work :(
There is one old example from AIXPRO in the Shopware Forum but that didn't work either...

Plesk sets up NGINX and installs mod_http2 for APACHE (a2enmod http2) only together with nginx infront... otherwise mod_http2 is not available. (would be interesting if h2push by apache works through nginxproxy)

And as I! can't run nginx only for sure i'll run apache only and as i got a dedicated system with 32gb ram i would go for mod_php and a bit ram for maria; but plesk is more like windows 2k and you'll get mod_php5 and http/1.1, gd without webp.. ;)

Enough hate for PLESK! ;-)
It could be so easy to manage a server for shopware with plesk :) INNOVATERS!

You did try h2push in your PageSpeed plugin right? Can you mesure that advantage of h2push?

**Comment by Hotte512** [comment]
btw. it works to exchange the gd.so with a new one where u compiled php (same version of course) with  webp enabled.
