### ISSUE TITLE
Plugin generates transparent pictures

### ISSUE THREAD

**Issue by riegerjan** [shyim/ShyimWebP#2]
Hi,
I've tried ShyimWebP plugin in Shopware, instalation was completely ok, so was the thumbnails generation. But when I opened my shop in browser, most of pictures was empty (only transparet color). 
I used Google Chrome v62.0.3202.89 64bit, I looked on server via FTP dirrectly to the folder with .webp picture and there was transparent picture too. So the problem isn't on the browser's site.
Mozilla doesn't support .webp format and use .jpg - in Mozilla my shop works with .jpg pictures right.

Can someone please explain me, what did I wrong and give me some clue to fix it?
Thanks

**Comment by shyim** [comment]
Can you send me a example jpg file which is transparent in webp?

**Comment by riegerjan** [comment]
Hi, thanx for answer, here I send the picture that was generated by  
the plugin. Dirrectly downloaded via FTP from media/../../picture.webp

Cituji Shyim <notifications@github.com>:

**Comment by shyim** [comment]
I guess you cannot send the image from mail answer :D.

**Comment by riegerjan** [comment]
Dne 14.11.2017 v 9:12 Shyim napsal(a):

**Comment by riegerjan** [comment]
[glassbong_200x200.zip](https://github.com/shyim/ShyimWebP/files/1470003/glassbong_200x200.zip)
.webp isn't supported to send here, it's in the zip

**Comment by shyim** [comment]
Could you send me also the jpg file. So i can check whats the difference between format

**Comment by riegerjan** [comment]
![glassbong_200x200](https://user-images.githubusercontent.com/33249631/32770335-8b7182c2-c91f-11e7-8503-2444987fe974.jpg)
here it is :)

**Comment by shyim** [comment]
Hey, sorry for the late answer. I checked with the same Image on PHP 7.2.2 and cannot reproduce the issue.

**Comment by shyim** [comment]
Can you test with the latest version again? There is a fix, which could fix that also.
