### ISSUE TITLE
Is there a webp generated img for the original (Fullsize) Picture?

### ISSUE THREAD

**Issue by Hotte512** [shyim/ShyimWebP#4]
As I try to serve webp for the Category Images ( {media path={**$category.media.path**|regex_replace:"/\.jpg$/i":".webp"}} ) it looks like they are not existing - right? and this might be senseful.

Do you know a clue to get a) thumbs for $category.media.path || b) webp for fulsize || c) a better hint?

btw. some images from "Emotion Product Box" seem not to serve webp, may be not all the time?
on the 13Inch Laptop it serves none from Einkaufswelt:)
Webpagetest gets some on EKW:`https://www.webpagetest.org/result/180213_H8_db38cde36e07cb5756c2436e2bd2243c/1/details/#waterfall_view_step1`

ArticleDetail page comes up just with small thumbs as webp and Listing does not (Laptop)

I'll have a look on Desktop tomorrow.. seems to be different on Laptop.
Viele Grüße aus Kölle

update: it looks like the system is not serving much webp:
![image](https://user-images.githubusercontent.com/12100810/36180825-434a68f6-1122-11e8-8e57-f743938a4f99.png)

**Comment by shyim** [comment]
There are many sections, which does not provide currently webp images.
I will add the orginal image also as webp image in the next commits

**Comment by shyim** [comment]
Has been fixed in the meanwhile
