### ISSUE TITLE
How to subscribe webp to jquery.last-seen-products.js ?

### ISSUE THREAD

**Issue by Hotte512** [shyim/ShyimWebP#8]
Would you give me a hint on how to get webp source in  jquery.last-seen-products.js :-)
so i could try to WebP Last-Seen section :-)

console.log(data);
told me that it needs te be added to the data function, but sadly i don't know how :-)

otherwise i just could str_replace the extension and hope that the webp file is there :-D

THX :-D

**Comment by shyim** [comment]
You have to overwrite that place here: https://github.com/shopware/shopware/blob/5.5/themes/Frontend/Bare/frontend/index/index.tpl#L191 and add the new variables.

But a simple replace could do it also... 🙈

**Comment by Hotte512** [comment]
Thank you i already searched a long time 😈 

replace would do, but what if there is no .webp?
AND i already can do replacements... 

but isn't replacing that whole block insecure (update)? :-/

**Comment by shyim** [comment]
You dont have to overwrite code.
Append that block frontend_index_header_javascript_data
and modifiy the variable lastSeenProductsConfig :)

**Comment by shyim** [comment]
You have to clear once your local storage :)

**Comment by Hotte512** [comment]
Incognito mode should be enough? JS: image.sourceSetWebp; is still undefined
Or isn't it image.sourceSetWebp but i already tried image.web.sourceSet...

![image](https://user-images.githubusercontent.com/12100810/49551516-ca515480-f8ef-11e8-9594-91987e03890a.png)

**Comment by shyim** [comment]
I mean that so https://github.com/shyim/ShyimWebP/commit/99af5b68c13c7003478e573f8c0c0baf818e28aa#diff-216191de9d9d3c5e3545761a262458f4R3 :)

**Comment by Hotte512** [comment]
thank you, i do not get the js :-/ but I'm not a developer at all.
But I think I found a small typo

You need a pizza, a composter or some wood ?
